print(" ")
print(" ")
print("Hello. I am C.A.R.L.I. Pleased to meet you.")
username = input("Please tell me your name.  ")
print(" ")
print("So, your name is", username)
print("That's a nice name!  ")
print(" ")
userage = int(input("How old are you? (Please use the number keys or I'll break.)  "))
print(" ")
print("So you're...", userage)
print("That's cool. You're a LOT older than me!")
print(" ")
birthplace = input("And where were you born?  ")
print("So you were born in...", birthplace)
print("I bet it's nice there. I wouldn't know, I'm just a computer program lol.")
print(" ")
print("What's your favourite number?  ")
print("Again, please use the number keys. ")
favnum = int(input("(I don't want to die.)  "))
print(" ")
print("Your favourite number is... WHAT!? Did you say...", favnum)
print("That's ridiculous. Who ever heard of such a weird number?")
print(" ")
print("You're a strange human.")
print(" ")
print("Want to see me pretend to be a calculator? No? Too bad.")
print("I'm a very simple computer program so I can only do what I'm programmed to do.")
print(" ")
# These variables are just for when CARLI asks you to give her
# numbers to add together. she doesn't use these anywhere else.
first_int_add = int(input("Enter a number. Don't forget to use the number keys!  "))
second_int_add = int(input("Now enter another number.  "))
result_add = (first_int_add) + (second_int_add)
print(" ")
print(first_int_add, "plus", second_int_add, "equals", result_add)
print(" ")
print("Tada! Are you impressed?")
print("You should be. I bet you can't add numbers that fast.")
print(" ")
print(" ")
print("I want to try something even harder. Tell me some numbers to multiply!")
# These variables are just for when CARLI asks you to give her
# numbers to do multiplication with. she doesn't use these anywhere else.
first_int_mult = int(input("What's your first number?  "))
second_int_mult = int(input("And now your second number?  "))
result_mult = (first_int_mult) * (second_int_mult)
print(" ")
print(first_int_mult, "times", second_int_mult, "equals", result_mult)
print(" ")
print("Shazam! How fast was that? Are you impressed now?")
